# This Dockerfile only used for setting up a local Postgres DB for testing
version: "3"

services:
  transaction-db-service:
    image: pocketfoundation/transaction-http-db:latest
    container_name: test-http-db
    restart: always
    ports:
      - 8080:8080
    environment:
      CONNECTION_STRING: postgres://postgres:pgpassword@transaction-db:5432/?sslmode=disable # pragma: allowlist secret
      API_KEYS: test_api_key
      MAX_SERVICE_RECORD_BATCH_SIZE: 1
      MAX_RELAY_BATCH_SIZE: 1
    depends_on:
      transaction-db:
        condition: service_healthy

  transaction-db:
    image: pocketfoundation/test-transaction-postgres:latest
    container_name: transaction-http-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 3
