# This Dockerfile only used for setting up a local Postgres DB for testing
version: "3"

services:
  test-database:
    image: pocketfoundation/test-transaction-postgres:latest
    container_name: test-transaction-http-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 3
